version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/supersecure123   # ✅ minimum 8 caractères
    volumes:
      - neo4j-data:/data
    restart: unless-stopped

  api:
    build: ./backend   # ⚠️ assure-toi que ton dossier backend existe ici
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - neo4j
    restart: unless-stopped

volumes:
  mongo-data:
  neo4j-data:
