version: '3.8'
services:
  mongo:
    image: mongo
    ports: ["27017:27017"]
  redis:
    image: redis
    ports: ["6379:6379"]
  neo4j:
    image: neo4j
    ports: ["7474:7474", "7687:7687"]
    environment:
      - NEO4J_AUTH=neo4j/test
  api:
    build: ./api
    ports: ["8000:8000"]
    depends_on:
      - mongo
      - redis
      - neo4j
